from pathlib import Path
import re

index=Path('index.html').read_text()
site=Path('assets/site.js').read_text()
email_hook=Path('assets/email-hook.js').read_text()
styles=Path('assets/styles.css').read_text()

# Extended guest profile and introduction fields.
old='''<div class="form-grid"><div><label data-i18n="phone">Phone</label><input id="guestPhone" autocomplete="tel"></div><div><label data-i18n="country">Country</label><input id="guestCountry" autocomplete="country-name"></div></div><label data-i18n="guests">Guests</label><select id="guestCount"></select><label data-i18n="message">Message</label><textarea id="message" rows="4"></textarea>'''
new='''<div class="form-grid"><div><label data-i18n="phone">Phone</label><input id="guestPhone" autocomplete="tel"></div><div><label data-i18n="country">Country</label><input id="guestCountry" autocomplete="country-name" required></div></div><div class="form-grid guest-profile-grid"><div><label>Age</label><input id="guestAge" type="number" min="18" max="120" required></div><div><label>Sex</label><select id="guestSex" required><option value="">Select</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="other">Other</option><option value="prefer_not_to_say">Prefer not to say</option></select></div></div><label>Languages</label><input id="guestLanguages" required placeholder="English, German, Sinhala"><label>Hobbies</label><input id="guestHobbies" placeholder="Travel, photography, cooking …"><label>Have you stayed with us before?</label><select id="guestReturning" required><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select><label data-i18n="guests">Guests</label><select id="guestCount"></select><label data-i18n="message">Message / introduction</label><p class="field-help" id="introHelp">Please introduce yourself properly: tell us who you are, why you are visiting Frankfurt and anything useful for your stay.</p><textarea id="message" rows="6" minlength="20" required></textarea>'''
if old not in index: raise SystemExit('booking form snippet changed')
index=index.replace(old,new,1)
index=index.replace('Your request remains pending and does not block the dates. If the host approves it, you will receive a limited-time payment link.','Your request remains pending until the host confirms it. Your card is saved securely now and is charged automatically 14 days before check-in. Cancellations more than 14 days before check-in receive a full refund; cancellations within 14 days are non-refundable.',1)
index=index.replace('Pending requests do not block dates. Once the host approves your request, a payment link becomes available for a limited time.','Check your booking, scheduled payment date and cancellation eligibility here.',1)

policy='''<section class="section cancellation-policy" id="cancellationPolicy"><div class="wrap"><div class="panel policy-card"><span class="section-kicker">Cancellation & payment</span><h2>Clear 14-day cancellation policy</h2><div class="policy-grid"><div><strong>More than 14 days before check-in</strong><p>Cancel for a full refund. If your card has not been charged yet, no charge is made.</p></div><div><strong>Within 14 days of check-in</strong><p>The booking is non-refundable. Confirmed bookings are charged automatically 14 days before check-in, or after confirmation when check-in is already within 14 days.</p></div></div><p class="muted">Your card is saved securely with Stripe. FrankiHolz does not store your card number.</p></div></div></section>'''
if 'id="cancellationPolicy"' not in index:
    index=index.replace('<section class="section" id="bookingStatusSection">',policy+'\n<section class="section" id="bookingStatusSection">',1)

# Add translations for new flow and make language switching update introduction help.
site=site.replace("payNow:'Pay now'", "payNow:'Continue',saveCard:'Save card securely',cancelBooking:'Cancel booking',cancelFullRefund:'Full refund available',cancelNonRefundable:'Non-refundable within 14 days',cardSaved:'Card saved securely',scheduledCharge:'Scheduled charge'",1)
site=site.replace("payNow:'Jetzt bezahlen'", "payNow:'Weiter',saveCard:'Karte sicher speichern',cancelBooking:'Buchung stornieren',cancelFullRefund:'Volle Erstattung möglich',cancelNonRefundable:'Innerhalb von 14 Tagen nicht erstattungsfähig',cardSaved:'Karte sicher gespeichert',scheduledCharge:'Geplante Belastung'",1)
site=site.replace("$('message').placeholder=tr('messagePlaceholder');", "$('message').placeholder=tr('messagePlaceholder');if($('introHelp'))$('introHelp').textContent=currentLang==='de'?'Bitte stellen Sie sich kurz vor: Wer sind Sie, warum besuchen Sie Frankfurt und was sollten wir für Ihren Aufenthalt wissen?':'Please introduce yourself properly: tell us who you are, why you are visiting Frankfurt and anything useful for your stay.';",1)

start=site.find("$('bookingForm').addEventListener('submit'")
end=site.find("document.querySelectorAll('.lang-btn')",start)
if start<0 or end<0: raise SystemExit('booking/status block not found')
new_block=r'''$('bookingForm').addEventListener('submit',async e=>{
 e.preventDefault();const out=$('bookingResult');out.innerHTML='';if(!selectedRoom||!start||!end){out.innerHTML=`<div class="notice">${tr('chooseDatesFirst')}</div>`;return}if(rangeBlocked(start,end)){out.innerHTML=`<div class="notice">${tr('selectedBlocked')}</div>`;return}
 const languages=$('guestLanguages').value.split(/[,;]/).map(x=>x.trim()).filter(Boolean);const intro=$('message').value.trim();
 if(languages.length===0||intro.length<20){out.innerHTML=`<div class="notice">${currentLang==='de'?'Bitte Sprache(n) angeben und eine kurze Vorstellung mit mindestens 20 Zeichen schreiben.':'Please add at least one language and a short introduction of at least 20 characters.'}</div>`;return}
 const payload={p_room_id:selectedRoom.id,p_check_in:start,p_check_out:end,p_guest_name:$('guestName').value.trim(),p_guest_email:$('guestEmail').value.trim(),p_guest_phone:$('guestPhone').value.trim(),p_guest_country:$('guestCountry').value.trim(),p_guests:Number($('guestCount').value),p_message:intro,p_language:currentLang,p_guest_age:Number($('guestAge').value),p_guest_sex:$('guestSex').value,p_guest_languages:languages,p_guest_hobbies:$('guestHobbies').value.trim(),p_guest_returning:$('guestReturning').value==='yes'};
 const isDevelop=location.hostname==='frankiholz.shipstatic.com'||location.hostname==='localhost'||location.hostname==='127.0.0.1';const rpcName=isDevelop?'frankiholz_create_booking_v2':'frankiholz_create_booking';const rpcPayload=isDevelop?payload:{p_room_id:payload.p_room_id,p_check_in:payload.p_check_in,p_check_out:payload.p_check_out,p_guest_name:payload.p_guest_name,p_guest_email:payload.p_guest_email,p_guest_phone:payload.p_guest_phone,p_guest_country:payload.p_guest_country,p_guests:payload.p_guests,p_message:payload.p_message,p_language:payload.p_language};
 const submit=e.currentTarget.querySelector('button[type=submit]');const old=submit.textContent;submit.disabled=true;submit.textContent=currentLang==='de'?'Anfrage wird gespeichert …':'Saving request …';
 const {data,error}=await sb.rpc(rpcName,rpcPayload);if(error){submit.disabled=false;submit.textContent=old;out.innerHTML=`<div class="notice">${escapeHtml(error.message)}</div>`;await loadCalendar();return}const b=data?.[0];
 out.innerHTML=`<div class="notice success">${tr('requestSent')} ${tr('reference')} <b>${escapeHtml(b.reference)}</b>. ${tr('estimated')} <b>${money(b.total_price)}</b>.</div>`;
 if(isDevelop){try{submit.textContent=currentLang==='de'?'Sichere Kartenseite wird geöffnet …':'Opening secure card setup …';const r=await fetch(`${CFG.supabaseUrl}/functions/v1/frankiholz-create-authorization-test`,{method:'POST',headers:{'Content-Type':'application/json','apikey':CFG.supabaseKey},body:JSON.stringify({reference:b.reference,email:payload.p_guest_email})});const j=await r.json();if(!r.ok||!j.checkout_url)throw new Error(j.error||'Could not open Stripe setup');location.href=j.checkout_url;return}catch(err){out.innerHTML+=`<div class="notice">${escapeHtml(err.message)}</div>`}}
 submit.disabled=false;submit.textContent=old;start=end=null;updateSummary();e.target.reset();await loadCalendar();
});

async function cancelCurrentBooking(ref,email,out){if(!confirm(currentLang==='de'?'Möchten Sie diese Buchung wirklich stornieren?':'Do you really want to cancel this booking?'))return;const r=await fetch(`${CFG.supabaseUrl}/functions/v1/frankiholz-cancel-booking-test`,{method:'POST',headers:{'Content-Type':'application/json','apikey':CFG.supabaseKey},body:JSON.stringify({reference:ref,email})});const j=await r.json().catch(()=>({}));if(!r.ok){out.innerHTML+=`<div class="notice">${escapeHtml(j.error||'Cancellation failed')}</div>`;return}out.innerHTML=`<div class="notice success">${j.refundable?(currentLang==='de'?'Buchung storniert. Volle Erstattung gilt.':'Booking cancelled. Full refund applies.'):(currentLang==='de'?'Buchung storniert. Innerhalb von 14 Tagen ist sie nicht erstattungsfähig.':'Booking cancelled. It is non-refundable within 14 days.')}</div>`;}

$('checkStatusBtn').onclick=async()=>{const ref=$('statusReference').value.trim(),email=$('statusEmail').value.trim(),out=$('statusResult');if(!ref||!email){out.innerHTML=`<div class="notice">${tr('enterRefEmail')}</div>`;return}const isDevelop=location.hostname==='frankiholz.shipstatic.com'||location.hostname==='localhost'||location.hostname==='127.0.0.1';const {data,error}=await sb.rpc(isDevelop?'frankiholz_booking_status_v2':'frankiholz_booking_status',{p_reference:ref,p_email:email});if(error){out.innerHTML=`<div class="notice">${escapeHtml(error.message)}</div>`;return}const b=data?.[0];if(!b){out.innerHTML=`<div class="notice">${tr('noBooking')}</div>`;return}const paymentLabel=String(b.payment_status||'not_started').replaceAll('_',' '),action=b.payment_url&&b.payment_status==='awaiting_payment'?`<a class="btn secondary" href="${b.payment_url}" style="display:inline-block;text-decoration:none;margin-top:12px">${tr('payNow')}</a>`:'';const due=isDevelop&&b.charge_due_at?`<br>${tr('scheduledCharge')}: <b>${new Date(b.charge_due_at).toLocaleString(currentLang==='de'?'de-DE':'en-DE')}</b>`:(b.payment_due_at?`<br>${tr('paymentDeadline')}: ${new Date(b.payment_due_at).toLocaleString(currentLang==='de'?'de-DE':'en-DE')}`:'');const policy=isDevelop?(b.cancel_refund_eligible?`<div class="status-policy refundable">${tr('cancelFullRefund')}</div>`:`<div class="status-policy nonrefundable">${tr('cancelNonRefundable')}</div>`):'';const cancel=isDevelop&&b.booking_status!=='cancelled'?`<button class="btn ghost" id="cancelBookingBtn" type="button" style="margin-top:12px">${tr('cancelBooking')}</button>`:'';out.innerHTML=`<div class="notice ${b.payment_status==='paid'?'success':''}"><b>${escapeHtml(b.reference)}</b> · ${escapeHtml(b.room_name)}<br>${b.check_in} → ${b.check_out} · ${money(b.total_price)}<br>${tr('booking')}: <b>${escapeHtml(b.booking_status)}</b> · ${tr('payment')}: <b>${escapeHtml(paymentLabel)}</b>${due}${policy}${action}${cancel}</div>`;$('cancelBookingBtn')?.addEventListener('click',()=>cancelCurrentBooking(ref,email,out));};
'''
site=site[:start]+new_block+site[end:]

# Trigger request email for both legacy and v2 booking RPCs.
email_hook=email_hook.replace("if(name==='frankiholz_create_booking'", "if((name==='frankiholz_create_booking'||name==='frankiholz_create_booking_v2')",1)

styles += '''\n\n/* September 2026 guest profile + 14-day payment policy */\n.field-help{margin:4px 0 8px;font-size:12px;color:var(--muted,#667a80);line-height:1.5}.guest-profile-grid{margin-top:10px}.cancellation-policy{padding-top:0}.policy-card{border-color:rgba(19,112,109,.2);background:linear-gradient(135deg,#f5fbf9,#fff)}.policy-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.policy-grid>div{border:1px solid #dce8e5;border-radius:14px;padding:14px;background:#fff}.policy-grid strong{display:block;color:#0c3447;margin-bottom:6px}.policy-grid p{margin:0;line-height:1.55}.status-policy{margin-top:10px;padding:8px 10px;border-radius:10px;font-size:12px;font-weight:700}.status-policy.refundable{background:#e9f8ef;color:#17633b}.status-policy.nonrefundable{background:#fff2e6;color:#9a4d10}@media(max-width:700px){.policy-grid{grid-template-columns:1fr}}\n'''

Path('index.html').write_text(index)
Path('assets/site.js').write_text(site)
Path('assets/email-hook.js').write_text(email_hook)
Path('assets/styles.css').write_text(styles)
